todo/models.py
from todo import db

class User(db.Model):

    __tablename__ = 'user'

    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(150), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(200), nullable=False)

class Todo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=True)
    user = db.relationship('User', backref='Todo')
    title = db.Column(db.String(100))
    desc = db.Column(db.Text())
    complete = db.Column(db.Boolean)

todo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, EmailField
from wtforms.fields.simple import PasswordField
from wtforms.validators import DataRequired, Length, EqualTo, Email

class TodoForm(FlaskForm):
    title = StringField("제목", validators=[DataRequired()])
    desc = TextAreaField("내용", validators=[DataRequired()])

class UserCreationForm(FlaskForm):
    username = StringField("유저이름", validators=[DataRequired(), Length(min=3,max=32)])
    password1 = StringField("비번", validators=[DataRequired(), EqualTo('password2', "불일치")])
    password2 = StringField("비번2", validators=[DataRequired()])
    email = EmailField('이메일', validators=[DataRequired(), Email()])

class UserLoginForm(FlaskForm):
    username = StringField("유저이름", validators=[DataRequired(),Length(min=3, max=25)])
    password = PasswordField("비밀번호", validators=[DataRequired()])

todo/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
import config
from flask_bcrypt import Bcrypt

db = SQLAlchemy()
migrate = Migrate()
bcrypt = Bcrypt()

def create_app():
    app = Flask(__name__)
    #-- 클래스를 통채로 전달
    # print(app.config)
    app.config.from_object(config)
    
    # ORM
    db.init_app(app)
    migrate.init_app(app, db)

    #bcrypt
    bcrypt.init_app(app)

    # Blueprint
    from .views import main_view, signup_view
    app.register_blueprint(main_view.bp)
    app.register_blueprint(signup_view.bp)

    # Model
    from todo import models

    return app

todo/views/main_view.py
from flask import Blueprint, render_template, request, url_for, g
from werkzeug.utils import redirect
from todo.models import Todo
from todo import db
from todo.forms import TodoForm


bp = Blueprint("main", __name__, url_prefix='/')

#-- ORM 연습
"""
db.session.qeury(Todo).filter(Todo.complete == False).all()
db.session.query(Todo).filter_by(conplete = Fasle).all()
Todo.query.filter(Todo.complete == False).all
"""

#-- 리스트 보기
@bp.route('/')
def index():
    incomplete = Todo.query.filter_by(complete=False).all()
    complete = Todo.query.filter_by(complete=True).all()
    return render_template("todo/todo_list.html", incomplete=incomplete, complete=complete)

#-- 생성
@bp.route("/add", methods=["POST","GET"])
def create():
    form = TodoForm()
    if request.method == "POST" and form.validate_on_submit():
        t = Todo(title=form.title.data, desc=form.desc.data, user_id= g.user.id, complete = False)
        db.session.add(t)
        db.session.commit()
        # Blueprint에서 url_for 사용할 땐 <블루프린트 명.함수명>으로 써야 한다.
        return redirect(url_for('main.index'))
    return render_template('todo/todo_create.html', form=form)

#-- 세부사항 보기
@bp.route("/detail/<int:id>")
def detail(id):
    t = Todo.query.filter_by(id=id).first()
    return render_template("todo/todo_detail.html", t=t)

#-- 수정
@bp.route("/update/<int:id>", methods=["POST", "GET"])
def update(id):
    t = Todo.query.filter_by(id=id).first()
    form = TodoForm(obj=t)
    if request.method =="POST":
        if form.validate_on_submit():
            t.title = form.title.data
            t.desc = form.desc.data
            t.complete = not t.complete
            print(form.desc)
            db.session.commit()
            return redirect(url_for('main.index'))
    else:
        return render_template('todo/todo_update.html',form=form, t=t)

#-- 삭제
@bp.route("/delete/<int:id>")
def delete_todo(id):
    t = Todo.query.filter_by(id=id).first()
    db.session.delete(t)
    db.session.commit()
    return redirect(url_for('main.index'))

todo/views/signup_view.py
from flask import Blueprint, render_template, url_for, flash, session, request, g
from werkzeug.utils import redirect
# from werkzeug.security import generate_password_hash
from todo.models import User
from todo import db
from todo.forms import UserCreationForm, UserLoginForm
from todo import bcrypt

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/signup/', methods=["GET","POST"])
def signup():
    form = UserCreationForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(
                username = form.username.data,
                # password = generate_password_hash(form.password1.data),
                # password = form.password1.data,
                password =  bcrypt.generate_password_hash(form.password1.data),
                email = form.email.data
            )
            print(user.password)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash("이미 있는 사용자")
    else:
        form = UserCreationForm()
    return render_template('signup/main_signup.html', form=form)


@bp.route('/login/', methods=["GET","POST"])
def login():
    form = UserLoginForm()
    if request.method == "POST" and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username = form.username.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif user.password != form.password.data:
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('signup/login.html', form=form) 

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)
        # print(g.user.id, g.user.password, g.user.email, sep="\n")
        """
        g.user에는 User객체의 정보가 들어간다.
        
        ***************출력값**************
        * 1 / wjdrlfwns / admin@admin.com *
        ***********************************
        """

@bp.route("/logout")
def logout():
    session.clear()
    print("로그아웃 완료")
    return redirect(url_for('auth.login'))

todo/templates/signup/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>로그인</title>
</head>
<body>
    <div class="container my-3">
        <form method="post" class="post-form">
            {{ form.csrf_token }}
            <div class="form-group">
                <label for="username">사용자 이름</label>
                <input type="text" class="form-control" name="username" id="username"
                       value="{{ form.username.data or '' }}">
            </div>
            <div class="form-group">
                <label for="password">비밀번호</label>
                <input type="password" class="form-control" name="password" id="password"
                       value="{{ form.password.data or '' }}">
            </div>
            <button type="submit" class="btn btn-primary">로그인</button>
        </form>
    </div>
</body>
</html>

todo/templates/signup/main_signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회원가입</title>
</head>
<body>
    <div class="container my-3">
        <form class="post-form" method="post" action="/auth/signup/">
            {{ form.csrf_token }}
            <div class="form-group">
                <label for="username">사용자 이름</label>
                <input type="text" class="form-control" name="username" id="username"
                       value="{{ form.username.data or '' }}">
            </div>
            <div class="form-group">
                <label for="password1">비밀번호</label>
                <input type="password" class="form-control" name="password1" id="password1"
                       value="{{ form.password1.data or '' }}">
            </div>
            <div class="form-group">
                <label for="password2">비밀번호 확인</label>
                <input type="password" class="form-control" name="password2" id="password2"
                       value="{{ form.password2.data or '' }}">
            </div>
            <div class="form-group">
                <label for="email">이메일</label>
                <input type="text" class="form-control" name="email" id="email"
                       value="{{ form.email.data or '' }}">
            </div>
            <button type="submit" class="btn btn-primary">생성하기</button>
        </form>
    </div>
</body>
</html>

todo/templates/todo/todo_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>할일 생성</title>
</head>
<body>
    <div class="container">
        <h5 class="my-3 border-bottom pb-2">할 일 등록</h5>
        <form action="/add" method="post" class="post-form my-3">
            {{ form.csrf_token }}
            <tr>
                <td>
                {{ form.title.label }}
                {{ form.title() }}
                </td>
                <td>
                {{ form.desc.label }}
                {{ form.desc() }}
                </td>
            </tr>
            <button type="submit" class="btn btn-primary">저장하기</button>
        </form>
</body>
</html>

todo/templates/todo/todo_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>상세 목록</title>
</head>
<body>
    {{ t.title }} 
    <br>
    {{ t.desc }}
    <br>
    {% if t.complete %}
        <h4>완료</h4>
    {% else %}
        <h4>미완료</h4>
    {% endif %}
    <hr>
    <a href="{{ url_for('main.index') }}">리스트로</a>
    <a href="{{ url_for('main.update', id=t.id) }}">수정</a>
    <a href="{{ url_for('main.delete_todo', id=t.id)}}">삭제</a>

</body>
</html>

todo/templates/todo/todo_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>오늘 할 일!!!</title>
</head>
<body>
    <div>
        <a href="{{ url_for('main.create') }}" class="btn btn-primary">할일 등록하기</a>
    </div>
    <hr>
    <div>
    {% for todo in incomplete %}
        <p>오늘할 일: <a href="{{ url_for('main.detail', id=todo.id)}}">{{ todo.title }}</a></p> 
        {% if todo.complete == False %}
            <h5>미완료</h5>
        {% endif %}
    {% endfor %}
    </div>
    <div>
        {% for finish in complete %}
            <p>한 일: <a href="{{ url_for('main.detail', id=finish.id) }}">{{ finish.title }}</a></p>
            {% if finish.complete %}
                <h5>완료</h5>
            {% endif %}
        {% endfor %}
    </div>
</body>
</html>

todo/templates/todo/todo_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo_Update</title>
</head>
<body>
    <form  method="POST" action="/update/{{t.id}}">
        {{ form.csrf_token }}
        <tr>
            <td>제목</td>
            <td><input type="text" name="title" class="form-control" value={{t.title}}></td>
            <br>
            <td>내용</td>
            <td><input type="text" name="desc" value={{t.desc}}></td>
        </tr>   
        <hr>
        <tr>
            <td colspan="2"><input type="submit" value="Edit"></td>
        </tr>
    </form>
</body>
</html>